out data error_stale_prepared_values {
    message: str
}

out data cart_item {
    name: str
    price: int
    product_id: str
    quantity: int
}

out entity cart {
    out order_id: str?
    value items: map[k = str, v = cart_item] = { }
    value prepared_subtotal: int?
    value prepared_tax: int?

    run {
        out! :error?

        wait(order_id != nil)!
    }

    out func checkout {
        out order_id: str?
        out! :error?

        if prepared_subtotal, prepared_tax := prepared_subtotal?, prepared_tax? {
            items := array::from_iter(iter = items.values_iter).result
            result := checkout_apply(items, prepared_subtotal, prepared_tax)!
            outer.order_id, order_id = result.order_id, result.order_id
        } else {
            return! error::simple(message = "checkout_prepare must be called before checkout")
        }
    }

    out func checkout_prepare {
        out subtotal: int
        out tax: int
        out! :error?

        items := array::from_iter(iter = items.values_iter).result
        result := checkout_prepare_apply(items)!
        prepared_subtotal, subtotal = result.subtotal, result.subtotal
        prepared_tax, tax = result.tax, result.tax
    }

    out func item_add {
        in product_id: str
        in quantity = 1
        out! :error?

        if existing := items.get(key = product_id)? {
            existing.quantity += quantity
        } else {
            product := product_lookup(product_id)!
            items.set(
                key = product_id,
                value = cart_item(
                    product_id,
                    product.name,
                    product.price,
                    quantity,
                ),
            )
        }
    }

    out noblock func item_remove {
        in product_id: str
        in quantity = 1

        if existing := items.get(key = product_id)? {
            existing.quantity -= quantity
            if existing.quantity <= 0 {
                items.remove(key = product_id)
            }
        }
    }

    out view func items_get {
        out items_list = array::from_iter(iter = items.values_iter).result
    }
}

# TODO: demonstrate HTTP invocation pattern
extern checkout_apply {
    in items: array[t = cart_item]
    in prepared_subtotal: int
    in prepared_tax: int
    out order_id: str
    # Can return error_stale_prepared_values if items changed since prepare
    out! :error?
}

# TODO: demonstrate HTTP invocation pattern
extern checkout_prepare_apply {
    in items: array[t = cart_item]
    out subtotal: int
    out tax: int
    out! :error?
}

extern product_lookup {
    in product_id: str
    out name: str
    out price: int
    out! :error?
}
