
# TODO(cretz): Prelude?
import duralade.duration
import duralade.error
import duralade.logger
import duralade.policy

out fob item {
  in out {
    id: str
    product_id: str
    quantity: str
  }
}

out fob state {
  in outmut {
    items = arr[item]()
    email: str
    done = false
    checkout_id: str?
  }
}

out fob checkout_info {
  in out {
    opaque_card_ref: str
    opaque_shipping_details_ref: str
  }
}

extern fob do_checkout {
  in :state
  in :checkout_info
  in policy = policy(start_to_close_timeout: duration(seconds: 30))
  out :error?
  out checkout_id: str
}

extern fob send_abandoned_cart_email {
  in :state
  in policy = policy(start_to_close_timeout: duration(seconds: 30))
  out :error?
}

out fob shopping_cart {
  in out :state

  var lock = false

  # Send abandoned cart email in background
  var timer = start sleep(:duration(days: 5))
  start fob {
    wait done timer
    # Ignore timer failure (cancel) or already done
    if timer.error || state.done {
      return
    }
    var send_res = send_abandoned_cart_email(state:)
    if send_res.error {
      logger.warning(message: "Failed sending abandoned cart email", error: send_res.error)
    }
  }

  # Wait until checked out
  # TODO: Or cancel? Can wait get interrupted by cancel? Needs to
  wait state.checkout_id != ""
}

out fob shopping_cart.add_item {
  in :item
  out :error?

  # TODO: Better mutex that can take block or something?
  wait !lock
  lock = true
  defer { lock = false }
  defer { timer.reset }

  if state.done {
    error("Cart done")!
  }
  for i in state.items {
    if i.id == item.id {
      # The "!" operator works if the item is an error _or_ is a fob with error? inside
      error("Item already exists")!
    }
  }
  state.items.add(item)
}

out fob shopping_cart.remove_item {
  in id: str
  out :error?

  wait !lock
  lock = true
  defer { lock = false }
  defer { timer.reset }

  if state.done {
    error("Cart done")!
  }
  for i in state.items {
    if i.id == id {
      state.items.remove(i)
      return
    }
  }
  error("Item not found")!
}

out fob shopping_cart.checkout {
  in :checkout_info
  out :error?

  wait !lock
  lock = true
  defer { lock = false }

  # Mark done, but if failed, we can mark undone
  state.done = true

  var res = do_checkout(state:, checkout_info:)
  if res.error {
    state.done = false
    res!
  }
  state.checkout_id = res.id
}