
# TODO(cretz): Preludes...
import duralade.duration
import duralade.error
import duralade.logger
import duralade.policy
import duralade.sleep

out fob email_details {
  in out {
    email_address: str
    message: str
  }
}

extern fob send_email {
  in :email_details
  in policy = policy()

  out :error?
}

out fob subscription {
  in email_address: str
  in :duration

  out :error?
  out subscribed = true
  out emails_sent = 0

  logger.info(message: "Subscription created", email_address:)

  out view fob status {
    out subscribed = subscribed
    out emails_sent = emails_sent
  }

  out fob unsubscribe {
    subscribed = false
  }

  # Send first email
  logger.info(message: "Sending welcome email", email_address:)
  emails_sent += 1
  send_email(:email_details(email_address:, message: "Welcome! Looks like you've been signed up!"))!

  # Run forever
  for {
    # Wait for timer or until no longer subscribed
    select {
      case sleep(duration:)! {
        # Do nothing
      }
      case wait !subscribed {
        # Send farewell email
        emails_sent += 1
        send_email(:email_details(email_address:, message: "Your subscription has been canceled. Sorry to see you go!"))!
        return
      }
    }

    # Send email
    emails_sent += 1
    send_email(:email_details(email_address:, message: "This is yet another email in the Subscription fob"))!
  }
}